### ISSUE TITLE
v0.8.1 tarball hash not matching

### ISSUE THREAD

**Issue by SamWhited** [ortuman/jackal#100]
Hi,

Recently the AUR package for Jackal broke because the source tarball hash is different from the expected hash. I was wondering if the authors force pushed a new tag and if so if they could clarify what is in the new v0.8.1 release. If not, I'll manually verify the package and assume GitHub did something odd.

Thanks,
Sam

**Comment by ortuman** [comment]
Hi! 👋 

I personally force pushed the tag, which from a functional PoV only fixes a bug in XEP-0163 module. Sorry for the inconvenience. 🙏

**Comment by SamWhited** [comment]
Thanks for the clarification. From a packaging (and general user sanity :) ) perspective, it would be nice if people could depend on the tags and tarballs not to change, it might be better to release a v0.8.2 or whatever in the future (this is what patch releases are for, in fact). Thanks!

**Comment by ortuman** [comment]
I'll bear that in mind for future changes. Thanks! :)
