### ISSUE TITLE
Invalid PgSQL being executed when upserting presences

### ISSUE THREAD

**Issue by SamWhited** [ortuman/jackal#114]
The SQL on [`storage/pgsql/presences.go:157`](https://github.com/ortuman/jackal/blob/f5647c18c27c2c5769a00ae876c5531c34fa3356/storage/pgsql/presences.go#L157) appears to be for MySQL or something similar, but it is in the Postgres package:

https://github.com/ortuman/jackal/blob/f5647c18c27c2c5769a00ae876c5531c34fa3356/storage/pgsql/presences.go#L157

This is causing warnings like the following on sign in:

> ⚠️ [WRN] xep0115/entity_caps:118 - pq: syntax error at or near "DUPLICATE"

**Comment by ortuman** [comment]
fixed @ https://github.com/ortuman/jackal/pull/116
