### ISSUE TITLE
Multi-Session Nicks

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#121]
Can you add Jackal XMPP Server informations here?
- https://wiki.xmpp.org/web/Multi-Session_Nicks

**Comment by Neustradamus** [comment]
@ortuman: It has not been added...

**Comment by ortuman** [comment]
Sorry but It won't. This is a one man project and I have to wisely choose my priorities, and unfortunately XEP-0045 is not among them.

**Comment by Neustradamus** [comment]
@ortuman: It is not solved, please re-open this ticket.
