### ISSUE TITLE
XEP-0114: Components

### ISSUE THREAD

**Issue by manuel-rubio** [ortuman/jackal#122]
Is it planned to add support for components?

**Comment by ortuman** [comment]
👋 hi @manuel-rubio!

ATM I'm exclusively working on a new service rebump (to refactor most of the codebase and add cluster support).

However, when done, component support is expected to be a priority task. 😄

**Comment by ortuman** [comment]
👋  Hi @manuel-rubio.  Let you know that the latest release [v0.50.0](https://github.com/ortuman/jackal/releases/tag/v0.50.0) already offers support for jabber components (XEP-0114).

In the example config file there's an snippet showing how to define a components listener.

Thanks for the suggestion and hope you find it useful.  🙇
