### ISSUE TITLE
-PLUS problem

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#124]
@ortuman: Can you look the problem: https://github.com/TelepathyIM/wocky/issues/2?
- https://github.com/TelepathyIM/wocky/issues/2#issuecomment-686768095

**Comment by Neustradamus** [comment]
@ortuman: Can you look?

**Comment by ortuman** [comment]
@Neustradamus could you confirm this is still an issue on [latest release](https://github.com/ortuman/jackal/releases/tag/v0.50.0)?

**Comment by ortuman** [comment]
Case was [solved](https://github.com/TelepathyIM/wocky/issues/2#issuecomment-794553780) 👍
