### ISSUE TITLE
Transfer into org?

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#125]
@ortuman: Can you move this repository into the jackal-xmpp organization?
- https://github.com/jackal-xmpp

**Comment by Neustradamus** [comment]
@ortuman: This project is now dead?

**Comment by ortuman** [comment]
No it isn't. ATM, I'm totally focused on a project revamp to provide cluster support among other things. I expect it to hace it ready in the next 2-3 months. Thanks for the patience. 🙇‍♂️

**Comment by Neustradamus** [comment]
@ortuman: Thanks for your reply.

But why it is not possible to transfer this repo into the organization?

**Comment by ortuman** [comment]
Not a priority now, but will be done when ready.

**Comment by ortuman** [comment]
For trying to understand better. What's the point of transfering it into .org? I've been thinking about this recently, and since this is a on man project I'd personally would leave it as is (at least for now).

**Comment by Neustradamus** [comment]
With this logic, please move all from https://github.com/jackal-xmpp into your personal account ;)

Or all into the organization ^^

One person or several people, it is not a problem to have an organization place.

Please change your account status from private to public here: https://github.com/orgs/jackal-xmpp/people.

Your are cited in README, there are your commits, you are in organization, ...

**Comment by ortuman** [comment]
Sorry, but I don't see any advantages in migrating to .org, and yet I do see the drawbacks, such as having to adapt all the code and spending valuable time.
