### ISSUE TITLE
Run jackal on shared host?

### ISSUE THREAD

**Issue by petrk94** [ortuman/jackal#13]
Hello,
I would like to know whether jackal is running on a shared host, Im using uberspace, but there is no docker possibility and another ways are not easy enough to run a own XMPP server on it.

Thanks

**Comment by ThomasLeister** [comment]
I assume as long as you have an own IP address to which you can attach Jackal it should be possible to get Jackal running on a shared host. Simply speaking Jackal is just a binary that can be run as normal user. No root needed.

*(Note that I'm not aware of Uberspace's infrastructure details)*

**Comment by petrk94** [comment]
I will try it if I have time.
Thanks
