### ISSUE TITLE
Feature request: XEP-0313: Message Archive Management

### ISSUE THREAD

**Issue by ortuman** [ortuman/jackal#140]
Add support for [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html)

**Comment by UniqueActive** [comment]
Hello, what is the status on this feature?
I saw that it was moved to "Done" at one point but then just removed and I couldn't find it in the list of features. :)

**Comment by ortuman** [comment]
👋 hi @UniqueActive 

This feature was put back in the backlog as other priorities came in. 

Currently, I've reprioritized it and I hope to have it ready for the next release (v0.62.0).

**Comment by ortuman** [comment]
Closing. [XEP-0313](https://xmpp.org/extensions/xep-0313.html) support already available starting from v0.62.0
