### ISSUE TITLE
MySQL database schema import:  Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by ThomasLeister** [ortuman/jackal#15]
When trying to import the MySQL schema for Jackal, my MySQL server reports an error: 

```
root@jackal1 ~/golang/src/github.com/ortuman/jackal # mysql jackal < sql/mysql.sql 
ERROR 1071 (42000) at line 6: Specified key was too long; max key length is 767 bytes
```
Note that I'm *not* using the official Oracle MySQL, but **MariaDB** as a MySQL server. Since MariaDB is e.g. shipped with Debian by default, I think this issue should be investigated and compatibility should be provided in the future. 

Maybe this issue from another Golang project is helpful? https://github.com/gogits/gogs/pull/4913/files

**Comment by ortuman** [comment]
You are right Thomas. The SQL script has been written having in mind MySQL 5.7

Let's make it compatible with MariaDB... :)

**Comment by ortuman** [comment]
Which version of MariaDB are you using @ThomasLeister?

Running the script with latest version *(MariaDB 10.2.14)* works fine. Could you confirm?

**Comment by ortuman** [comment]
Great! I'll update README.md to make it clear. Thank you for reporting!
