### ISSUE TITLE
ARM architecture and docker-compose.yml

### ISSUE THREAD

**Issue by uGeek** [ortuman/jackal#155]
Jackal seems like a project to be amazed! Congratulations.

Since Jackal is very lightweight, docker support is planned for ARM architecture such as the Raspberry Pi.

It would also be great to have a docker-compose to make mounting easier.

Thank you

**Comment by ortuman** [comment]
Thanks for the suggestion @uGeek . 👍 

Truth is I think this is a very good point, especially for those who want to try the service without having to configure/install anything.

**Comment by uGeek** [comment]
Thank you.

Waiting to try it...

**Comment by ortuman** [comment]
👋 Hi again @uGeek!

Already done.

Here are the [instructions](https://github.com/ortuman/jackal#docker-compose) to easily mount `jackal` server using docker compose. 

Hope you find it useful, and if you want to report any feedback, would be welcome. 😃
