### ISSUE TITLE
New maintainer(s) needed

### ISSUE THREAD

**Issue by ortuman** [ortuman/jackal#179]
I am stepping down as maintainer of the jackal project.

I am looking for one or more people with a track record of successfully maintaining an open source project. Potential maintainers can gain this experience by contributing to this project.

If you rely on the quality and ongoing maintenance of this project, then please get involved by helping to maintain this project or finding people to help maintain the project.

**Comment by Neustradamus** [comment]
@ortuman: After several requests: Any news for the move of this repo in the org?
- https://github.com/jackal-xmpp

The upstream need to be move and not a fork.

Thanks in advance.

**Comment by Neustradamus** [comment]
@ortuman: Have you found?

**Comment by etuttle** [comment]
I might be interested in helping out.  I contacted @ortuman directly via email to discuss.
