### ISSUE TITLE
Move into the organization

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#181]
Dear @ortuman, it is possible to migrate this repo into the jackal-xmpp organization?
- https://github.com/jackal-xmpp

I have requested you several times in the past.

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

A redirection from old to new place will be here...
No lost.

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

Thanks in advance.

Linked to:
- https://github.com/ortuman/jackal/issues/125

**Comment by ortuman** [comment]
Sorry, but this project isn't going to be moved to an jackal-xmpp organization. Thanks.

**Comment by Neustradamus** [comment]
@ortuman: It is strange, why?

I do not understand some are here, some into jackal-xmpp.

Can you remove the indentical fork: https://github.com/jackal-xmpp/jackal?

And maybe move all here and remove jackal-xmpp organization after if it is the solution.

Thanks in advance.
