### ISSUE TITLE
Refactor storage model to provide other alternatives besides an RDBMS / SQL db

### ISSUE THREAD

**Issue by prologic** [ortuman/jackal#189]
Is it worthwhile refactoring the code and some of the database related functions I see in the schema such that simpler/smaller installations can be deployed? For example using a BoltDB database?

**Comment by ortuman** [comment]
👋 @prologic 

The current repository [interface](https://github.com/ortuman/jackal/blob/main/pkg/storage/repository/repository.go#L20) already abstracts the application from the underlying used database. 

However, the real reason jackal doesn't support extra databases other than PgSQL is quite simple: time.

Having to maintain two different implementations would require me a precious time that I'd rather invest on some other features that IMO would add more value. 

Anyway, I like your idea of having smaller/simpler installations. And if possible, I'd consider it in the future. 😃

**Comment by ortuman** [comment]
@prologic this was finally implemented @ [v0.58.0](https://github.com/ortuman/jackal/releases/tag/v0.58.0)

And thanks for the suggestion. 🙇‍♂️

**Comment by prologic** [comment]
Oh this is great news! I might actually go stand up an instance of this now 🥳
