### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#19]
On the README (RFCs and XEPs support), it is possible to add version of XEPs?
https://github.com/ortuman/jackal/blob/master/README.md

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by stevenroose** [comment]
What are you most interested in here? The supported version of the XEP? Or the Jackal version that starts supporting the XEP?

**Comment by ortuman** [comment]
Added XEPs version to README.md. ([commit](https://github.com/ortuman/jackal/commit/1847ef942592ad6a56c981f62821f461b735ebcf))
