### ISSUE TITLE
buddy got disconnected on malformed xml message received

### ISSUE THREAD

**Issue by readyblue** [ortuman/jackal#2]
when you send some malformed xml to your buddy, the server disconnect your buddy.

this is example of what you need to send to get your buddy disconected:

`<test>test`

**Comment by readyblue** [comment]
checking this issue by sending well-formed and malformed xml message to different clients
1.) from Xabber to Pidgin:
msg:
<test></test> - passed fine and it is delivered (wel-formed xml message in text form)
<test>test - disconnects buddy on Pidgin immediately

2.) from Pidgin to Xabber:
msg:
<test></test> - does not deliver, but does not disconnect.
<test>test - disconnect buddy on Xabber immediately

all the messages are sent in clear test, in a way that user can type on its keyboard

**Comment by ortuman** [comment]
Fixed on 0.1.3 release. Thank you.
