### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by Neustradamus** [ortuman/jackal#20]
I have seen a beautiful logo but the XMPP logo has been updated last year, can you update it too?
https://github.com/ortuman/jackal/blob/master/doc/gopher.png

Source: https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by ortuman** [comment]
Sorry, but I don't see any clear difference between the current logo and the one included in the README.md file

**Comment by SamWhited** [comment]
@ortuman there was an issue in the XMPP Logo where the "arms" were being rendered in the wrong order. In your logo the orange color of the right arm renders over the left, even though in general the left arm is over the right. This has been fixed in the version of the logo on the XSFs site.

**Comment by ortuman** [comment]
Good point @SamWhited! I'll fix it asap. Thx!

**Comment by ortuman** [comment]
Fixed.

**Comment by Neustradamus** [comment]
@ortuman: Can you update the logo a new time?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by Neustradamus** [comment]
@ortuman: The logo in this repository is;
- https://github.com/ortuman/jackal/blob/master/.github/gopher.png

Can you update it with the good XMPP logo?
