### ISSUE TITLE
no pepper keys defined?

### ISSUE THREAD

**Issue by brianwoo** [ortuman/jackal#218]
Version: v0.58.0
Platform: Linux localhost 3.18.124-lineageos-g04ff888001f2 #1 SMP PREEMPT Mon Mar 14 05:04:42 UTC 2022 aarch64 Android
Subsystem: if known, please specify the affected core module name

I am getting the following error when starting jackal:
$ ./jackal
level=info ts=2022-03-17T19:29:57.042434572Z caller=jackal.go:188 msg="jackal is starting..." version=v0.58.0 go_ver=go1.17.8 go_os=android go_arch=arm64
2022/03/17 19:29:57 pepper: no pepper keys defined

**Comment by ortuman** [comment]
👋 hey @brianwoo!

Starting from v0.59.0 pepper keys are not mandatory to be set in order to bootstrap jackal. So go ahead, and give it a try!
