### ISSUE TITLE
Getting Started: go get won't work any more

### ISSUE THREAD

**Issue by march1993** [ortuman/jackal#221]
```shell
$ go get -d github.com/ortuman/jackal
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by SamWhited** [comment]
That means you're not in your project directory. Go to your project directory, make sure it's using modules, then run that again. If you're not familiar with modules, you'll need to do a `go mod init mymodule.com/whatever` in your project folder first. This tutorial can get you started: https://go.dev/doc/tutorial/create-module

**Comment by march1993** [comment]
When I'm in my project directory. Command 'go get' runs successfully. But `cd $GOPATH/src/github.com/ortuman/jackal` fails since neithor `GOPATH` nor `GOROOT` is set.

**Comment by ortuman** [comment]
Thanks for reporting! The `README.md` has been properly updated. 🙇‍♂️
