### ISSUE TITLE
In-Band registration: Support Captcha (XEP-0158)

### ISSUE THREAD

**Issue by ThomasLeister** [ortuman/jackal#27]
Nice to have: Captchas for In-Band registration.

https://xmpp.org/extensions/xep-0158.html#register

Background info: Some XMPP server operators turn off in-band registration because of misuse by spam bots. Most web registration interfaces support captchas, so this is a common approach how to handle registrations. 

Still this is not a really satisfying practise, since in-band registration exists for a reason and users are expecting to be able to register directly via their XMPP client (and not only via web). Therefore I'm asking to implement captchas for in-band registration.

*Note: Captchas should not be implemented via Google Recatchas, because avoiding Google and its services is a main reason why people use XMPP ;-) XMPP users tend to dislike links and dependencies  to/from "big players" for a good reason. Fortunately, there are some Golang captcha libraries out there, such as: https://github.com/dchest/captcha*

**Comment by ortuman** [comment]
Stale issue
