### ISSUE TITLE
META: Host a dev chat MUC on jackal.im

### ISSUE THREAD

**Issue by stevenroose** [ortuman/jackal#29]
An XMPP server project having an official Gitter?? :/ We can do better, right? :)

**Comment by ThomasLeister** [comment]
Maybe we can postpone that until Jackal runs stable? Because hosting a Jackal MUC with another XMPP server wouldn't be okay either ;-)

**Comment by stevenroose** [comment]
Yeah I thought about that :D That's fine. Can take a while though, I guess.

**Comment by genofire** [comment]
feel free to use my one - atm, till jackal is good enougth:
[![my server](https://inverse.chat/badge.svg?room=jackal@conference.chat.sum7.eu)](xmpp:jackal@conference.chat.sum7.eu?join")

**Comment by stevenroose** [comment]
@genofire That badge doesn't work for me..

**Comment by ThomasLeister** [comment]
@ortuman are there any advantages in using Gitter over a XMPP MUC? To be honest I'm not very familiar with Gitter, but I guess you have reasons for using it? 

*(not questioning your decision - just asking. I'm fine with Gitter, too.)*

**Comment by stevenroose** [comment]
It's easy and free, basically. And every github user automatically has an
account. I don't like the web interface it has. But they have an IRC
bridge. We can also just hoop up at #jackal@freenode
