### ISSUE TITLE
Time to change logo again?

### ISSUE THREAD

**Issue by ThomasLeister** [ortuman/jackal#31]
See https://blog.golang.org/go-brand

:wink:

**Comment by stevenroose** [comment]
I think a protest in the form of extensively keep using the Gopher everywhere is appropriate.

**Comment by SamWhited** [comment]
> I think a protest in the form of extensively keep using the Gopher everywhere is appropriate.

The gopher is not changing, and the logo has barely changed. This is the old logo, the new one is just a cleaned up version and a document that provides a design language for the pending website and blog redesign.

![https://golang.org/doc/go-logo-white.png](https://golang.org/doc/go-logo-white.png)
