### ISSUE TITLE
module: add XEP-0163 (Personal Eventing Protocol) support

### ISSUE THREAD

**Issue by link2xt** [ortuman/jackal#35]
It is not listed in the README so I assume it is not implemented.

PEP is required by OMEMO, so it is essential for any modern XMPP server.

**Comment by ortuman** [comment]
Next goal is to implement XEP-0163 (Personal Eventing Protocol). In fact, I'd like to enforce (if possible) OMEMO on jackal.

**Comment by ortuman** [comment]
Done @ https://github.com/ortuman/jackal/releases/tag/v0.7.0
