### ISSUE TITLE
stringprep.h

### ISSUE THREAD

**Issue by modInfo** [ortuman/jackal#39]
xml/jid.go:13:24: fatal error: stringprep.h: No such file or directory

**Comment by ortuman** [comment]
Make sure you have libidn installed before trying to build jackal.

**Comment by modInfo** [comment]
Works with libidn, but sql not

```
# mysql -h localhost -D jackal -u jackal -p < mysql.sql
Enter password:
ERROR 1071 (42000) at line 6: Specified key was too long; max key length is 767 bytes
```

**Comment by ortuman** [comment]
jackal requires MySQL 5.7+ or MariaDB 10.2+
