### ISSUE TITLE
users cannot change their password once modul 'XEP-0077: In-Band Registration' is disabled

### ISSUE THREAD

**Issue by readyblue** [ortuman/jackal#4]
let us present this use case:

I do not want to users can register new accounts, but I want to allow them to change their password, so I have change the config like this:

```
      # XEP-0077: In-Band Registration
      #- registration

```

at this point, users cannot change their password, 
yet no error is presented to them, nor no error on server log is found.

**Comment by readyblue** [comment]
correction, Pidgin does not report error, but it does not announce the message "your password has been changed" either.

**Comment by ortuman** [comment]
Added `allow_registration` option in mod_registration configuration...

in the exposed use case should look like this...

    mod_registration:
      allow_registration: no
      allow_change: yes
      allow_cancel: no
