### ISSUE TITLE
Pleaes tag using "v0.0.0" format for go module support

### ISSUE THREAD

**Issue by SamWhited** [ortuman/jackal#57]
[Go Modules](https://golang.org/doc/go1.11#modules) require tags of the form "v0.0.0" (with the "v" prefix). Please consider tagging this way in the future to make releases compatible with modules and possibly adding additional tags on the existing tagged commits. Thanks!

**Comment by ortuman** [comment]
Thanks for pointing this out Sam! All release tags has been already renamed. Also hope to port to go modules soon enough. Thanks!
