### ISSUE TITLE
Hash password

### ISSUE THREAD

**Issue by muety** [ortuman/jackal#62]
I think it is a good practice to save a user's password to the database encrypted instead of in plain text.

**Comment by ThomasLeister** [comment]
Oh, isn't the password encrypted? I haven't checked myself, but I consider this very important. Maybe bcrypt or something similar could be used for that :-)

**Comment by stevenroose** [comment]
Hmm, perhaps read up a bit on best practices for that. I'd guess a
user-specific salt is also needed. Also, I don't think they need to be
encrypted, just hashed. With a user-specific salt. You could create the
salt by hashing some metadata about the user (username, first password,
time of creation) together with some random (to avoid problems with bad
PRNGs) and just store the salt next to the password.

**Comment by n1try** [comment]
Of course, hashing the password is what I meant, sorry for the confusion.
I am not very used to the best practices there, but I guess just normally hashing `md5`- or `SHA-1`-hashing the password would already be sufficient.

**Comment by ThomasLeister** [comment]
Please don't use md5 or sha1. MD5 has been broken a long time ago and sha1 was broken in 2016 or 2017 ... sooo... better choose something serious ;-)

**Comment by SamWhited** [comment]
Even if SHA-1 weren't broken, the SHA series of hashes is designed to be fast, making them entirely inappropriate for protecting passwords in a database for which you really want a slow key-derivation function such as argon2 (the current OWASP recommendation, IIRC) or PBKDF.2 (like SCRAM uses). For XMPP it is common to store SCRAM bits as if the user had logged in with SCRAM-SHA-1 (that way if you support that auth mechanism you can use them directly, and if you're doing PLAIN you can treat it just like any other hash.

**Comment by zet4** [comment]
Since no one has so far, I would propose SCrypt or it's brother BCrypt.

**Comment by roobre** [comment]
+1 for Bcrypt, implementing it seems straightforward too: https://godoc.org/golang.org/x/crypto/bcrypt

**Comment by vetterfl** [comment]
The problem is, you can not use hashing with digest-md5 authentication (which is still the default on client side IMHO). It relies on both the server and the client sharing the same password. https://prosody.im/doc/plain_or_hashed

**Comment by SamWhited** [comment]
> which is still the default on client side IMHO

It's not, no one uses DIGEST-MD5 anymore. It's also completely broken, so there's not much point in supporting it when legacy clients also support PLAIN (which is basically the same thing except you can do hashing properly), and most clients support SCRAM-SHA-1 (where you can store hashed scram bits).

**Comment by vetterfl** [comment]
Ah, OK. I'll definitely look in to SCRAM then. And you already mentioned that 3 posts earlier (and I just over-read that).

**Comment by vetterfl** [comment]
OK, one more question. You would have to decide which hashing algorithm to use upon registration. So either SHA-1 or SHA-256 so you could only support one SASL mechanism and PLAIN. How to decide? Or am I totally wrong again? How do other server handle that? I ran prosody a while ago but didn't spend much time looking into SASL. Passwords were hashed, though.

**Comment by SamWhited** [comment]
Since the hash in SCRAM is only used as part of the HMAC it doesn't really matter much so long as it's cryptographically secure. Right now most things support SCRAM-SHA-1 since support is required by RFC 6120 and not much supports SCRAM-SHA-256 (Prosody and Conversations do, but not a whole lot else).

Supporting SCRAM-SHA-1 and PLAIN (using proper password storage techniques for plain auth and only storing scram bits for SCRAM-SHA-1 auth) is probably enough to cover 99% of clients in the wild.

**Comment by roobre** [comment]
I'd say non-plain auth methods are a bit outdated nowadays, where most clients and servers use and support TLS. I think Bcrypt storage with PLAIN auth is the best option. Of supporting other stuff like SCRAM would be nice, but I see it way less important.

**Comment by jcbrand** [comment]
> I'd say non-plain auth methods are a bit outdated nowadays

If you're using PLAIN and going through a proxy, like a BOSH connection manager, then your password could get leaked.

**Comment by ortuman** [comment]
👋 Hi everyone! Just wanted to share with you that since [latest release](https://github.com/ortuman/jackal/releases/tag/v0.50.0) we only store user passwords in hashed form into database (no more plain texts). Also, and additional security layer was added by providing support for salted+pepper password hashes. 

If there's any other suggestion in this regard feel free to open an issue. 🙇
