### ISSUE TITLE
Add Tor support for c2s communication

### ISSUE THREAD

**Issue by robzon** [ortuman/jackal#69]
Add an option to listen for incoming client connections via Tor hidden service.

Removed s2s for now as I'm not sure if this would even be possible currently.

**Comment by licaon-kter** [comment]
Umm, this does not need server support, just edit **/etc/tor/torrc**
```
HiddenServiceDir /var/lib/tor/hidden_service_v2
HiddenServicePort 5222 127.0.0.1:5222

HiddenServiceDir /var/lib/tor/hidden_service_v3
HiddenServiceVersion 3
HiddenServicePort 5222 127.0.0.1:5222
```

**Comment by robzon** [comment]
I was thinking about embedded support, but now I realize embedding makes much more sense for clients rather than servers. It seems the only thing that's needed on the server side is the ability to connect to other servers via onion addresses (s2s).
