### ISSUE TITLE
error code 503 on sending the message

### ISSUE THREAD

**Issue by readyblue** [ortuman/jackal#7]
This was spotted on Xabber client, when two buddies communicate. From certain point only one of them is able to send the messages , the other one is getting error and cannot send any more message. Subscription is both,both in the DB.

[error-503-red-cross.txt](https://github.com/ortuman/jackal/files/1707081/error-503-red-cross.txt)

Still cannot reproduce what possibly could cause this issue.

**Comment by ortuman** [comment]
Ok. According to the log file seems pretty clear that messages are being sent to an already disconnected stream. Is there any way I can reproduce this very same issue? Also, maybe this has something to do with the recently added 'resource conflict' policy feature. Playing with different values changes this behavior? Thanks in advance!

**Comment by readyblue** [comment]
I have tried changing the 'resource conflict' even before I have submit this issue. It has no effect on it.

This one is tough to reproduce, I do not even know how does it happen. Suddenly my friend and I were connected via mobile data with Xabber and it happens right there.

**Comment by ortuman** [comment]
Mmmmmm, may this happen while one of you has the Xabber application in background???

**Comment by readyblue** [comment]
@ortuman well we both have Xabber in the background most of the time, so it is very possible

**Comment by ortuman** [comment]
and do you see any previous disconection in the logs?

**Comment by readyblue** [comment]
I have found this
`[DBG] stream:838 - SEND: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><malformed-request/></failure>`

attaching full log:
[full-503-error.txt](https://github.com/ortuman/jackal/files/1711652/full-503-error.txt)

**Comment by ortuman** [comment]
very useful! thanks!
I see why these messages are being resent as error

`
<message to="user_2@example.com/xabber_dndsar61" id="wf3GR-1872" type="chat"><body>still-cannot-deliver</body><thread>lA2BJhSAmwCX</thread><active xmlns="http://jabber.org/protocol/chatstates"/><request xmlns="urn:xmpp:receipts"/></message> 
`

notice that resource is in lowercase, though previously the stream was authenticated like `Xabber_DNdsar61`

**Comment by ortuman** [comment]
`
Else if the JID is of the form <user@domain/resource> and no available resource matches the full JID, the recipient's server (a) SHOULD silently ignore the stanza (i.e., neither deliver it nor return an error) if it is a presence stanza, (b) MUST return a <service-unavailable/> stanza error to the sender if it is an IQ stanza, and (c) SHOULD treat the stanza as if it were addressed to <user@domain> if it is a message stanza. 
`

so in case the JID doesn't match any active resource, the message SHOULD be delivered to all available resources... :)

I fix it asap!
(BTW, later I'll tackel the `malformed-request` issue)

Thanks for the report!!!

**Comment by ortuman** [comment]
Fixed on `0.1.9` release
