### ISSUE TITLE
Session establishment (as per rfc3921) should not be required by the server

### ISSUE THREAD

**Issue by robzon** [ortuman/jackal#73]
rfc6121 (which obsoletes rfc3921) no longer requires session to be explicitly established by the client:

From [rfc6121](https://xmpp.org/rfcs/rfc6121.html#intro-summary):

> Interoperability Note: [RFC3921] specified one additional precondition: formal establishment of an instant messaging and presence session. Implementation and deployment experience has shown that this additional step is unnecessary. However, for backward compatibility an implementation MAY still offer that feature. This enables older software to connect while letting newer software save a round trip.

jackal still requires the session to be explicitly open.

**Comment by ortuman** [comment]
fixed at 7cb0c4d63302258eebeda0ab698353c54bfb5c0b
