### ISSUE TITLE
Implement custom auth mechanism

### ISSUE THREAD

**Issue by ortuman** [ortuman/jackal#82]
Implement external gateway auth mechanism via HTTP.

**Comment by creativenoobie** [comment]
@ortuman Any updates on this mate?

**Comment by ortuman** [comment]
👋 Hey @creativenoobie ! Let you know that [latest release](https://github.com/ortuman/jackal/releases/tag/v0.50.0) already offers support for external authentication mechanism.

Jackal provides this functionality through [grpc](https://grpc.io/). Authenticator [proto definition](https://github.com/jackal-xmpp/jackal-proto/blob/master/jackal/proto/authenticator/v1/authenticator.proto#L24-L27) can be found at [jackal-proto](https://github.com/jackal-xmpp/jackal-proto) repository.

In the example config file you can find an [snippet](https://github.com/ortuman/jackal/blob/master/example.config.yaml#L70-L74) that shows how to configure external auth integration. 

Please, if you have any doubt feel free to drop an issue or ping me on [gitter](https://gitter.im/jackal-im/jackal).
