### ISSUE TITLE
Suggestion: optional gateway mode for Mattermost?

### ISSUE THREAD

**Issue by poVoq** [ortuman/jackal#86]
Sorry for posting a suggestion only...

Anyways, this project would be ideal I think to include a gateway mode for the Mattermost chat system. They already have a similar system for IRC that allows connecting to Mattermost with any IRC client and have previously suggested that a similar approach could also be used to allow Mattermost to act as a XMPP server backend.

The relevant code for the minimalist IRC server can be found here:
https://github.com/42wim/matterircd

Both Mattermost and the MatterIRCd are written in Go, just like Jackal.

@42wim could probably provide some feedback on the feasibility of this suggestion.

Thanks in advance for looking into this suggestion :)

**Comment by ortuman** [comment]
Going to close this issue as currently there are higher priorities to be tackled. Anyway, thanks for the proposal. 🙇
