### ISSUE TITLE
Can't go get without errors

### ISSUE THREAD

**Issue by ThomasLeister** [ortuman/jackal#9]
Hi, I've tried to install Jackal on my test virtual server running Debian 9 Stretch. I've installed Golang 1.7.4:

```
root@jackal1 ~/golang # go version
go version go1.7.4 linux/amd64
```

... and all the build requirements for Jackal dependencies. Now ```go get github.com/ortuman/jackal``` results in this error messages:

```
root@jackal1 ~/golang # go get github.com/ortuman/jackal
# github.com/dgraph-io/badger
src/github.com/dgraph-io/badger/db.go:1108: y.LSMSize.Get(db.opt.Dir).(*expvar.Int).Value undefined (type *expvar.Int has no field or method Value)
src/github.com/dgraph-io/badger/db.go:1109: y.VlogSize.Get(db.opt.Dir).(*expvar.Int).Value undefined (type *expvar.Int has no field or method Value)
src/github.com/dgraph-io/badger/level_handler.go:66: undefined: sort.Slice
src/github.com/dgraph-io/badger/level_handler.go:71: undefined: sort.Slice
src/github.com/dgraph-io/badger/levels.go:253: undefined: sort.Slice
src/github.com/dgraph-io/badger/levels.go:355: undefined: sort.Slice
src/github.com/dgraph-io/badger/levels.go:442: undefined: sort.Slice
src/github.com/dgraph-io/badger/transaction.go:233: undefined: sort.Slice
src/github.com/dgraph-io/badger/value.go:665: undefined: sort.Slice
```

Is there anything I can do about it... or is this a bug? 

> [...] This will retrieve the code and install the jackal server application into your $GOBIN path.

There's no binary in my $GOBIN after `go get`.

**Comment by ortuman** [comment]
Go 1.9+ is required!

**Comment by ThomasLeister** [comment]
Now it works! I already had the idea of installing a more recent version of go instead of using the version from the Debian repos. But I did a mistake while installing Go manually and the packaged (outdated) version was still functional. 

So now with my fixed setup it works! :-) Thanks anyway!
