### ISSUE TITLE
a little new here, could use some help.

### ISSUE THREAD

**Issue by gravestristen** [ortuman/jackal#94]
i just ran through all the steps and set up the server but I don't know how to connect to the server correctly or create an account on it, I'm using profanity as my xmpp client.
edit: also am i able to make multi user rooms and if so how?

**Comment by kaffeekanne** [comment]
Since profanity does not support in band registration (IBR) yet you might want to create an account with another client like gajim or Conversations. Afterwards connecting with profanity should work.
